service: project-name

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
    packager: 'yarn'
  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  runtime: nodejs8.10

functions:
  api:
    name: api
    handler: src/handler.handler
    events: [ { http: 'ANY /function/api' }, { http: 'ANY /function/api/{proxy+}' } ]
  filesCreate:
    name: files-create
    handler: src/files.createFile
    events: [ { http: 'POST /files' } ]
    environment:
      PLUGIN: localStorage
  filesRead:
    name: files-read
    handler: src/files.readFile
    environment:
      PLUGIN: localStorage
    events:
      - http:
          path: files/{proxy+}
          method: get
          contentHandling: CONVERT_TO_BINARY
          request:
            parameters:
              paths:
                src: true