name: webiny-cms-project

gateway:
  component: '../../node_modules/@webiny/serverless-function'
  inputs:
    description: API Gateway
    code: ./api-gateway/build
    handler: handler.handler
    root: ./api-gateway
    hook: yarn build:deploy
    env:
      STAGE: __wby_inject__
      API_HOST: https://idumrbbokj.execute-api.us-east-1.amazonaws.com/dev
files:
  component: '../../node_modules/@webiny/serverless-function'
  inputs:
    code: ./api-service-files/build
    handler: handler.handler
    root: ./api-service-files
    hook: yarn build:deploy
    env:
      MONGODB_SERVER: __wby_inject__
      MONGODB_DB_NAME: __wby_inject__
      WEBINY_JWT_SECRET: __wby_inject__
i18n:
  component: '../../node_modules/@webiny/serverless-function'
  inputs:
    code: ./api-service-i18n/build
    handler: handler.handler
    root: ./api-service-i18n
    hook: yarn build:deploy
    env:
      MONGODB_SERVER: __wby_inject__
      MONGODB_DB_NAME: __wby_inject__
      WEBINY_JWT_SECRET: __wby_inject__
forms:
  component: '../../node_modules/@webiny/serverless-function'
  inputs:
    code: ./api-service-forms/build
    handler: handler.handler
    root: ./api-service-forms
    hook: yarn build:deploy
    env:
      MONGODB_SERVER: __wby_inject__
      MONGODB_DB_NAME: __wby_inject__
      WEBINY_JWT_SECRET: __wby_inject__
security:
  component: '../../node_modules/@webiny/serverless-function'
  inputs:
    code: ./api-service-security/build
    handler: handler.handler
    root: ./api-service-security
    hook: yarn build:deploy
    env:
      MONGODB_SERVER: __wby_inject__
      MONGODB_DB_NAME: __wby_inject__
      WEBINY_JWT_SECRET: __wby_inject__
pageBuilder:
  component: '../../node_modules/@webiny/serverless-function'
  inputs:
    code: ./api-service-page-builder/build
    handler: handler.handler
    root: ./api-service-page-builder
    hook: yarn build:deploy
    env:
      MONGODB_SERVER: __wby_inject__
      MONGODB_DB_NAME: __wby_inject__
      WEBINY_JWT_SECRET: __wby_inject__
api:
  component: '@serverless/api'
  inputs:
    endpoints:
      - path: /function/api
        method: ANY
        function: ${gateway}
      - path: /function/files
        method: ANY
        function: ${files}
      - path: /function/security
        method: ANY
        function: ${security}
      - path: /function/forms
        method: ANY
        function: ${forms}
      - path: /function/i18n
        method: ANY
        function: ${i18n}
      - path: /function/page-builder
        method: ANY
        function: ${pageBuilder}