language: node_js
sudo: false
node_js:
  - "6.10"
cache: yarn
branches:
  only:
    - master
    - development
install:
  - yarn install --ignore-engines
jobs:
  include:
    - stage: test
      script: yarn ci
    - stage: release
      node_js: "8.9.4"
      if: branch = master
      script: yarn release
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - webiny:rw9auyqJpDRRGcVmFCektrH5