language: node_js
sudo: false
node_js:
  - "8.9.4"
cache: yarn
branches:
  only:
    - master
    - development
    - testing-improvements
install:
  - yarn install --ignore-engines
jobs:
  include:
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test:build && yarn test:coverage:ci
    - stage: release
      if: branch = master
      script: yarn build && yarn release
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - webiny:rw9auyqJpDRRGcVmFCektrH5