language: node_js
sudo: false
node_js:
  - "node"
  - "6.10"
cache: yarn
install:
  - yarn install
script:
  - yarn ci
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - webiny:rw9auyqJpDRRGcVmFCektrH5