service: webinycms

provider:
  name: aws
  runtime: nodejs8.10
  profile: pavel

plugins:
  - serverless-offline
  - build-functions

package:
  individually: true
  exclude:
    - ./**

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    port: 9000
  webiny:
    local:
      functionsHost: http://localhost:${self:custom.serverless-offline.port}
      jwtSecret: MyS3cr3tK3Y!
      database:
        server: mongodb://localhost:27018
        httpServer: http://localhost:5001
        name: webinyjs
    dev:
      functionsHost: http://localhost:${self:custom.serverless-offline.port}
      jwtSecret: MyS3cr3tK3Y!
      database:
        server: mongodb+srv://webiny-sls:WGPhPPnHRK9LN4xW@webiny-sls-ddei2.mongodb.net/test?retryWrites=true
        name: webiny_sls

functions:
  api-gateway:
    handler: examples/functions/api-gateway/build/handler.handler
    environment:
      FUNCTIONS_HOST: ${self:custom.webiny.${self:custom.stage}.functionsHost}
      MONGODB_SERVER: ${self:custom.webiny.${self:custom.stage}.database.server}
      MONGO_HTTP_SERVER: ${self:custom.webiny.${self:custom.stage}.database.httpServer}
      MONGODB_DB_NAME: ${self:custom.webiny.${self:custom.stage}.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.${self:custom.stage}.jwtSecret}
    events:
      - http:
          path: /function/api/
          method: any
          cors: true
  api-service-files:
    handler: examples/functions/api-service-files/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.${self:custom.stage}.database.server}
      MONGO_HTTP_SERVER: ${self:custom.webiny.${self:custom.stage}.database.httpServer}
      MONGODB_DB_NAME: ${self:custom.webiny.${self:custom.stage}.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.${self:custom.stage}.jwtSecret}
    events:
      - http:
          path: /function/files/
          method: any
  api-service-security:
    handler: examples/functions/api-service-security/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.${self:custom.stage}.database.server}
      MONGO_HTTP_SERVER: ${self:custom.webiny.${self:custom.stage}.database.httpServer}
      MONGODB_DB_NAME: ${self:custom.webiny.${self:custom.stage}.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.${self:custom.stage}.jwtSecret}
    events:
      - http:
          path: /function/security/
          method: any
  api-service-page-builder:
    handler: examples/functions/api-service-page-builder/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.${self:custom.stage}.database.server}
      MONGO_HTTP_SERVER: ${self:custom.webiny.${self:custom.stage}.database.httpServer}
      MONGODB_DB_NAME: ${self:custom.webiny.${self:custom.stage}.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.${self:custom.stage}.jwtSecret}
    events:
      - http:
          path: /function/page-builder/
          method: any
  files:
    # This function handles local file uploads
    handler: examples/functions/files/build/handler.handler
    events:
      - http:
          path: /files/{key+}
          method: get
    package:
      include:
        - packages/files/build/handler.jwtSecret
  api-service-i18n:
    handler: examples/functions/api-service-i18n/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.${self:custom.stage}.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.${self:custom.stage}.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.${self:custom.stage}.jwtSecret}
    events:
      - http:
          path: /function/i18n/
          method: any
  api-service-forms:
    handler: examples/functions/api-service-forms/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.${self:custom.stage}.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.${self:custom.stage}.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.${self:custom.stage}.jwtSecret}
    events:
      - http:
          path: /function/forms/
          method: any
