service: webinycms

provider:
  name: aws
  runtime: nodejs8.10
  profile: pavel

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - build-functions

package:
  individually: true
  exclude:
    - ./**

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    port: 9000
  webiny:
    functionsHost: ${env:FUNCTIONS_HOST}
    jwtSecret: ${env:JWT_SECRET}
    database:
      server: ${env:DATABASE_SERVER}
      name: ${env:DATABASE_NAME}

functions:
  api-gateway:
    handler: examples/functions/api-gateway/build/handler.handler
    environment:
      FUNCTIONS_HOST: ${self:custom.webiny.functionsHost}
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /function/api/
          method: any
          cors: true
  api-service-files:
    handler: examples/functions/api-service-files/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /function/files/
          method: any
  api-service-security:
    handler: examples/functions/api-service-security/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /function/security/
          method: any
  api-service-page-builder:
    handler: examples/functions/api-service-page-builder/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /function/page-builder/
          method: any
  files:
    # This function handles local file uploads
    handler: examples/functions/files/build/handler.handler
    events:
      - http:
          path: /files/{key+}
          method: get
    package:
      include:
        - packages/files/build/handler.handler
  api-service-i18n:
    handler: examples/functions/api-service-i18n/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /function/i18n/
          method: any
  api-service-forms:
    handler: examples/functions/api-service-forms/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /function/forms/
          method: any
