service: webinycms

provider:
  name: aws
  runtime: nodejs8.10
  profile: pavel

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - build-functions

package:
  individually: true
  exclude:
    - ./**

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    port: 9000
  webiny:
    functionsHost: ${env:FUNCTIONS_HOST}
    jwtSecret: ${env:JWT_SECRET}
    database:
      server: ${env:DATABASE_SERVER}
      name: ${env:DATABASE_NAME}

functions:
  api-gateway:
    handler: examples/functions/code/api-gateway/build/handler.handler
    environment:
      FUNCTIONS_HOST: ${self:custom.webiny.functionsHost}
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
      SERVICE_FILES: http://localhost:9000/graphql/files
      SERVICE_I18N: http://localhost:9000/graphql/i18n
      SERVICE_PB: http://localhost:9000/graphql/page-builder
      SERVICE_SECURITY: http://localhost:9000/graphql/security
      SERVICE_FORMS: http://localhost:9000/graphql/forms
    events:
      - http:
          path: /graphql
          method: any
          cors: true
  api-service-files:
    handler: examples/functions/code/api-service-files/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /graphql/files/
          method: any
  api-service-security:
    handler: examples/functions/code/api-service-security/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /graphql/security/
          method: any
  api-service-page-builder:
    handler: examples/functions/code/api-service-page-builder/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /graphql/page-builder/
          method: any
  files:
    # This function handles local file uploads
    handler: examples/functions/code/files/build/handler.handler
    events:
      - http:
          path: /files/{key+}
          method: get
  api-service-i18n:
    handler: examples/functions/code/api-service-i18n/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /graphql/i18n/
          method: any
  api-service-forms:
    handler: examples/functions/code/api-service-forms/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /graphql/forms/
          method: any
  api-service-cms:
    handler: examples/functions/code/api-service-cms/build/handler.handler
    environment:
      MONGODB_SERVER: ${self:custom.webiny.database.server}
      MONGODB_DB_NAME: ${self:custom.webiny.database.name}
      WEBINY_JWT_SECRET: ${self:custom.webiny.jwtSecret}
    events:
      - http:
          path: /graphql/cms/
          method: any
