name: webiny-cms

site:
  component: "@webiny/serverless-app"
  inputs:
    description: Webiny Site
    hook: yarn build:${cli.env}
    root: ./site
    timeout: 30
admin:
  component: "@webiny/serverless-app"
  inputs:
    description: Webiny Admin
    hook: yarn build:${cli.env}
    root: ./admin

api:
  component: "@webiny/serverless-api-gateway"
  inputs:
    description: Serverless Site
    endpoints:
      - path: /admin/{key+}
        method: GET
        function: ${admin}
      - path: /admin
        method: GET
        function: ${admin}
      - path: /{key+}
        method: GET
        function: ${site}
      - path: /
        method: GET
        function: ${site}

cdn:
  component: "@webiny/serverless-aws-cloudfront"
  inputs:
    origins:
      - url: ${api.url}
