service: project-name

plugins:
  - serverless-offline
  - serverless-static

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, "us-east-1"}
  client:
    bucketId: ${opt:bucket, ""}
  api:
    source: ${opt:source, "dist"}
  static:
    path: ./static
    port: 8000

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${self:custom.region}
  role: ${opt:role, ""}

functions:
  api:
    name: '${self:service}-${self:custom.stage}-api'
    handler: ${self:custom.api.source}/handler.api
    events: [ { http: 'ANY /graphql' }, { http: 'ANY /graphql/{proxy+}' } ]
