service: project-name

plugins:
  - serverless-offline
  - serverless-plugin-cloudfront-lambda-edge

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, "us-east-1"}
  client:
    bucketId: ${opt:bucket, ""}
  api:
    source: ${opt:source, "dist"}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${self:custom.region}
  role: ${opt:role, ""}

functions:
  api:
    name: '${self:service}-${self:custom.stage}-api'
    handler: ${self:custom.api.source}/index.handler
    events: [ { http: 'ANY /graphql' }, { http: 'ANY /graphql/{proxy+}' } ]
