name: webiny-cms-project-apps

site:
  component: '../../node_modules/@webiny/serverless-app'
  inputs:
    code: ./site/build
    handler: handler.handler
    name: webiny-site
    description: Webiny Site
admin:
  component: '../../node_modules/@webiny/serverless-app'
  inputs:
    code: ./admin/build
    handler: handler.handler
    name: webiny-admin
    description: Webiny Admin

api:
  component: '@serverless/api'
  inputs:
    endpoints:
      - path: /admin/{key+}
        method: ANY
        function: ${admin}
      - path: /admin
        method: ANY
        function: ${admin}
      - path: /{key+}
        method: ANY
        function: ${site}
      - path: /
        method: ANY
        function: ${site}