name: webiny-files-service

graphql:
  component: "@webiny/serverless-function"
  inputs:
    memory: 128
    code: build
    description: Files GraphQL
    handler: handler.handler
    install:
      - handler.install
      - install.createData
      - install.createFiles
    root: ./
    hook: yarn build:deploy
    env:
      MONGODB_SERVER: __wby_inject__
      MONGODB_DB_NAME: __wby_inject__
      WEBINY_JWT_SECRET: __wby_inject__

api:
  component: "/Users/paveldenisjuk/webiny/js/aws-api-gateway"
  inputs:
    stage: prod
    name: "Files Microservice"
    description: "Microservice for files"
    endpointTypes: ['REGIONAL']
    endpoints:
      - path: "/graphql"
        method: ANY
        function: ${graphql.arn}
      - path: "/files/upload"
        method: ANY
        function: ${upload.arn}
